#!/usr/bin/env bash
# prints the all the domain names of the server if no
# options are specified, otherwise prints the specified
# parameters
domain_or_sub () {
	local dom="$1"
	local sub="$2"

	printf "The subdomain %s is a " "$2"
	dig "$sub"."$dom" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $4}'
	printf " record and points to "
	dig "$sub"."$dom" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{printf $5}'
	printf "\n"
}

if [ "$#" -eq 1 ]
then
	subs=("www" "lb-01" "web-01" "web-02")
	for sub in "${subs[@]}";
	do
		domain_or_sub "$1" "$sub"
	done
else
		domain_or_sub "$1" "$2"
fi
