#!/usr/bin/env bash
# This script installs nginx on my web server listening on port 80
# and puts "Hello world as the content when the server is requested

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html

sudo service nginx restart
