#!/usr/bin/env bash
# This script is a configuration of a brand new nginx server
# so that /redirect_me redirects to another page

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World' | sudo tee /usr/share/nginx/html/index.html

redirect="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}"
sudo sed -i "/server {/a $redirect" /etc/nginx/sites-available/default

service nginx start
