#!/usr/bin/env bash
# This script is a configuration of a brand new nginx server
# so that /redirect_me redirects to another page

apt-get -y update
apt-get -y install nginx

echo 'Hello World' > /var/www/html/index.html

sed -i '/server {/a \ \ \ \ location /redirect_me/ { return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; }' /etc/nginx/sites-available/default

service nginx start
