#!/usr/bin/env bash
# This script is a configuration of a brand new nginx server
# so that /redirect_me redirects to another page

apt-get -y update
apt-get -y install nginx

echo 'Hello World' > /var/www/html/index.html

redirect="location /redirect_me {
	return 301 https://apple.com;
}"

echo -e "$redirect" | sudo tee /etc/nginx/sites-available/default

service nginx restart
