#!/usr/bin/env bash
# This script configures a nginx server to have a custom
# 404 page that contains the string "Ceci n'est pas une page"

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/www/html/index.html

sed -i '/server {/a \ error_page 404 /index.html;\n\ \ location = /index.html {\n\ \ \ \ root /var/www/html;\n}' /etc/nginx/sites-available/default

service nginx restart
