#!/usr/bin/env bash
# This script configures a nginx server to have a custom
# 404 page that contains the string "Ceci n'est pas une page"

sudo apt-get update
sudo apt-get -y install nginx

echo 'Hello World' | sudo tee /usr/share/nginx/html/index.html

redirect="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}"
sudo sed -i "/server {/a $redirect" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404_page.html

sudo sed -i '/server {/a \ error_page 404 /custom_404_page.html;\n\ \ location = /custom_404_page.html {\n\ \ \ \  root /usr/share/nginx/html/;\n}' /etc/nginx/sites-available/default

sudo service nginx restart
