#!/usr/bin/env bash
# This script installs nginx on a server and and configures a custom http
# response header which is X-Served-By and the value of the header is
# the hostname of the server that nginx is running on.
sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World' | sudo tee /usr/share/nginx/html/index.html

redirect="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}"
sudo sed -i "/server {/a $redirect" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404_page.html

error_page="\\\terror_page 404 /custom_404_page.html;\n\tlocation = /custom_404_page.html {\n\t\troot /usr/share/nginx/html/;\n\t}"
sudo sed -i "/server {/a $error_page" /etc/nginx/sites-available/default

custom_header="\\\tlocation / {\n\t\tadd_header X-Served-By $HOSTNAME;\n\t}"
sudo sed -i "/server {/a $custom_header" /etc/nginx/sites-available/default

sudo service nginx restart
