#!/usr/bin/env bash
# This script installs and configures HAproxy on a load
# balancer server to send traffic to two servers using
# a roundrobin algorithm
sudo apt-get -y update
sudo apt-get -y install haproxy

haproxycfg="/etc/haproxy/haproxy.cfg"

cat <<EOL >> "$haproxycfg"
frontend my_frontend
	bind *:80
	mode http
	default_backend my_backend

backend my_backend
	balance roundrobin
	server 274773-web-01 34.234.203.112:80 check
	server 274773-web-02 35.153.33.42:80 check
EOL

sudo sh -c 'echo "ENABLED=1" > /etc/default/haproxy'

sudo service haproxy start
