#!/usr/bin/env bash
# This script creates a file /var/run/myscript.pid containing its pid, displays "To infinity and beyond" indefinitely, displays "I hate the kill command" when receiving a SIGTERM, displays "Y U no love me?!" when receiving SIGINT, deletes the file /var/run/myscript.pid and terminates itself when receiving SIGQUIT or SIGTERM
touch /var/run/myscript.pid
pgrep -f "/var/run/myscript.pid" > var/run/myscript.pid
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!; exit" SIGINT
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
