#!/usr/bin/env bash
# displays numbers from 1 to 100 and prints "FizzBuzz" if a number is a multiple of 3 and 5, "Fizz" if the number is a multiple of 3 and "Buzz" if the number is a multiple of 5
i=1
while ((i < 101)) 
do
	if ((i % 3 == 0)) && ((i % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((i % 3 == 0))
	then
		echo "Fizz"
	elif ((i % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	((i += 1))
done
