#!/usr/bin/env bash
# Displays the username, user id and home directory path in the contents of the file /etc/passwd
if [ -e "/etc/passwd" ]
then
	while read -r line
	do
		echo "$line" | cut -d ":" -f 1,3,6
	done < "/etc/passwd"
fi
