#!/usr/bin/env bash
# Displays the username, user id and home directory path in the contents of the file /etc/passwd
if [ -e "/etc/passwd" ]
then
	cut -d ":" -f 1,3,6 "/etc/passwd" | sed 's/\t/:/g' | while read -r line
	do
		echo "$line"
	done
fi
