#!/usr/bin/env bash
# This script prints sorted and numbered apache access log files ordered from the greatest to the lowest number of occurrences
awk '{print $1" "$9}' apache-access.log | sort | uniq -c | sort -nr
