#!/usr/bin/env bash
# This script prints the hours from 0 to 12, for each hour it prints minutes from 1 to 59
i=0
while ((i < 13))
do
	j=1
	echo "Hour: $i"
	while ((j < 60))
	do
		echo "$j"
		((j += 1))
	done

	((i += 1))
done
