#!/usr/bin/env bash
# This script prints the contents of the current directory in a list format where only the part of the name after the first dash is printed(the second field)
for i in *
do
	echo "$i" | cut -d "-" -f 2
done
