#!/usr/bin/env bash
# Prints the information about the "school" file
i="school"
if [ -e "$i" ]
then
	if [ -s "$i" ] && [ -f "$i" ]
	then
		echo "$i file exists"
		echo "$i file is not empty"
		echo "$i is a regular file"
	elif [ ! -f "$i" ] && [ -s "$i" ]
	then
		echo "$i file exists"
		echo "$i file is not empty"
	elif [ ! -s "$i" ] && [ -f "$i" ]
	then
		echo "$i file exists"
		echo "$i file is empty"
		echo "$i is a regular file"
	fi
else
	echo "$i file does not exist"
fi
